/* eslint-disable */
// @ts-nocheck
/*
* This file is a generated Typescript file for GRPC Gateway, DO NOT MODIFY
*/

export enum ErrorReason {
  ERROR_REASON_UNSPECIFIED = "ERROR_REASON_UNSPECIFIED",
  SERVICE_DISABLED = "SERVICE_DISABLED",
  BILLING_DISABLED = "BILLING_DISABLED",
  API_KEY_INVALID = "API_KEY_INVALID",
  API_KEY_SERVICE_BLOCKED = "API_KEY_SERVICE_BLOCKED",
  API_KEY_HTTP_REFERRER_BLOCKED = "API_KEY_HTTP_REFERRER_BLOCKED",
  API_KEY_IP_ADDRESS_BLOCKED = "API_KEY_IP_ADDRESS_BLOCKED",
  API_KEY_ANDROID_APP_BLOCKED = "API_KEY_ANDROID_APP_BLOCKED",
  API_KEY_IOS_APP_BLOCKED = "API_KEY_IOS_APP_BLOCKED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  RESOURCE_QUOTA_EXCEEDED = "RESOURCE_QUOTA_EXCEEDED",
  LOCATION_TAX_POLICY_VIOLATED = "LOCATION_TAX_POLICY_VIOLATED",
  USER_PROJECT_DENIED = "USER_PROJECT_DENIED",
  CONSUMER_SUSPENDED = "CONSUMER_SUSPENDED",
  CONSUMER_INVALID = "CONSUMER_INVALID",
  SECURITY_POLICY_VIOLATED = "SECURITY_POLICY_VIOLATED",
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_SCOPE_INSUFFICIENT = "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
  ACCOUNT_STATE_INVALID = "ACCOUNT_STATE_INVALID",
  ACCESS_TOKEN_TYPE_UNSUPPORTED = "ACCESS_TOKEN_TYPE_UNSUPPORTED",
}