// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registrar.proto

package registrar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NodeType int32

const (
	NodeType_TPM   NodeType = 0
	NodeType_GCP   NodeType = 1
	NodeType_AWS   NodeType = 2
	NodeType_AZURE NodeType = 3
)

var NodeType_name = map[int32]string{
	0: "TPM",
	1: "GCP",
	2: "AWS",
	3: "AZURE",
}

var NodeType_value = map[string]int32{
	"TPM":   0,
	"GCP":   1,
	"AWS":   2,
	"AZURE": 3,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}

func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{0}
}

type WorkloadType int32

const (
	WorkloadType_OCI WorkloadType = 0
	WorkloadType_BIN WorkloadType = 1
)

var WorkloadType_name = map[int32]string{
	0: "OCI",
	1: "BIN",
}

var WorkloadType_value = map[string]int32{
	"OCI": 0,
	"BIN": 1,
}

func (x WorkloadType) String() string {
	return proto.EnumName(WorkloadType_name, int32(x))
}

func (WorkloadType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{1}
}

type RegisterNodeRequest struct {
	JWT                  string        `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	NodeType             NodeType      `protobuf:"varint,2,opt,name=NodeType,proto3,enum=registrar.NodeType" json:"NodeType,omitempty"`
	Selectors            *SelectorList `protobuf:"bytes,3,opt,name=Selectors,proto3" json:"Selectors,omitempty"`
	NodeGroup            string        `protobuf:"bytes,4,opt,name=NodeGroup,proto3" json:"NodeGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterNodeRequest) Reset()         { *m = RegisterNodeRequest{} }
func (m *RegisterNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeRequest) ProtoMessage()    {}
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{0}
}

func (m *RegisterNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterNodeRequest.Unmarshal(m, b)
}
func (m *RegisterNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterNodeRequest.Marshal(b, m, deterministic)
}
func (m *RegisterNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeRequest.Merge(m, src)
}
func (m *RegisterNodeRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterNodeRequest.Size(m)
}
func (m *RegisterNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeRequest proto.InternalMessageInfo

func (m *RegisterNodeRequest) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

func (m *RegisterNodeRequest) GetNodeType() NodeType {
	if m != nil {
		return m.NodeType
	}
	return NodeType_TPM
}

func (m *RegisterNodeRequest) GetSelectors() *SelectorList {
	if m != nil {
		return m.Selectors
	}
	return nil
}

func (m *RegisterNodeRequest) GetNodeGroup() string {
	if m != nil {
		return m.NodeGroup
	}
	return ""
}

type RegisterWorkloadRequest struct {
	JWT                  string        `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	WorkloadType         WorkloadType  `protobuf:"varint,2,opt,name=WorkloadType,proto3,enum=registrar.WorkloadType" json:"WorkloadType,omitempty"`
	Selectors            *SelectorList `protobuf:"bytes,3,opt,name=Selectors,proto3" json:"Selectors,omitempty"`
	NodeGroup            string        `protobuf:"bytes,4,opt,name=NodeGroup,proto3" json:"NodeGroup,omitempty"`
	WorkloadName         string        `protobuf:"bytes,5,opt,name=WorkloadName,proto3" json:"WorkloadName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterWorkloadRequest) Reset()         { *m = RegisterWorkloadRequest{} }
func (m *RegisterWorkloadRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterWorkloadRequest) ProtoMessage()    {}
func (*RegisterWorkloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{1}
}

func (m *RegisterWorkloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterWorkloadRequest.Unmarshal(m, b)
}
func (m *RegisterWorkloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterWorkloadRequest.Marshal(b, m, deterministic)
}
func (m *RegisterWorkloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterWorkloadRequest.Merge(m, src)
}
func (m *RegisterWorkloadRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterWorkloadRequest.Size(m)
}
func (m *RegisterWorkloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterWorkloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterWorkloadRequest proto.InternalMessageInfo

func (m *RegisterWorkloadRequest) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

func (m *RegisterWorkloadRequest) GetWorkloadType() WorkloadType {
	if m != nil {
		return m.WorkloadType
	}
	return WorkloadType_OCI
}

func (m *RegisterWorkloadRequest) GetSelectors() *SelectorList {
	if m != nil {
		return m.Selectors
	}
	return nil
}

func (m *RegisterWorkloadRequest) GetNodeGroup() string {
	if m != nil {
		return m.NodeGroup
	}
	return ""
}

func (m *RegisterWorkloadRequest) GetWorkloadName() string {
	if m != nil {
		return m.WorkloadName
	}
	return ""
}

type RegisterResponse struct {
	SpiffeID             string   `protobuf:"bytes,1,opt,name=spiffeID,proto3" json:"spiffeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetSpiffeID() string {
	if m != nil {
		return m.SpiffeID
	}
	return ""
}

type GetAccountRequest struct {
	Selectors            *SelectorList `protobuf:"bytes,1,opt,name=Selectors,proto3" json:"Selectors,omitempty"`
	NodeType             NodeType      `protobuf:"varint,2,opt,name=NodeType,proto3,enum=registrar.NodeType" json:"NodeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{3}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetSelectors() *SelectorList {
	if m != nil {
		return m.Selectors
	}
	return nil
}

func (m *GetAccountRequest) GetNodeType() NodeType {
	if m != nil {
		return m.NodeType
	}
	return NodeType_TPM
}

type GetAccountResponse struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	NodeGroup            string   `protobuf:"bytes,2,opt,name=NodeGroup,proto3" json:"NodeGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{4}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *GetAccountResponse) GetNodeGroup() string {
	if m != nil {
		return m.NodeGroup
	}
	return ""
}

type Selector struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Selector) Reset()         { *m = Selector{} }
func (m *Selector) String() string { return proto.CompactTextString(m) }
func (*Selector) ProtoMessage()    {}
func (*Selector) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{5}
}

func (m *Selector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Selector.Unmarshal(m, b)
}
func (m *Selector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Selector.Marshal(b, m, deterministic)
}
func (m *Selector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selector.Merge(m, src)
}
func (m *Selector) XXX_Size() int {
	return xxx_messageInfo_Selector.Size(m)
}
func (m *Selector) XXX_DiscardUnknown() {
	xxx_messageInfo_Selector.DiscardUnknown(m)
}

var xxx_messageInfo_Selector proto.InternalMessageInfo

func (m *Selector) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Selector) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SelectorList struct {
	Selectors            []*Selector `protobuf:"bytes,1,rep,name=Selectors,proto3" json:"Selectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SelectorList) Reset()         { *m = SelectorList{} }
func (m *SelectorList) String() string { return proto.CompactTextString(m) }
func (*SelectorList) ProtoMessage()    {}
func (*SelectorList) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f352f3dd33231ae, []int{6}
}

func (m *SelectorList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelectorList.Unmarshal(m, b)
}
func (m *SelectorList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelectorList.Marshal(b, m, deterministic)
}
func (m *SelectorList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectorList.Merge(m, src)
}
func (m *SelectorList) XXX_Size() int {
	return xxx_messageInfo_SelectorList.Size(m)
}
func (m *SelectorList) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectorList.DiscardUnknown(m)
}

var xxx_messageInfo_SelectorList proto.InternalMessageInfo

func (m *SelectorList) GetSelectors() []*Selector {
	if m != nil {
		return m.Selectors
	}
	return nil
}

func init() {
	proto.RegisterEnum("registrar.NodeType", NodeType_name, NodeType_value)
	proto.RegisterEnum("registrar.WorkloadType", WorkloadType_name, WorkloadType_value)
	proto.RegisterType((*RegisterNodeRequest)(nil), "registrar.RegisterNodeRequest")
	proto.RegisterType((*RegisterWorkloadRequest)(nil), "registrar.RegisterWorkloadRequest")
	proto.RegisterType((*RegisterResponse)(nil), "registrar.RegisterResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "registrar.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "registrar.GetAccountResponse")
	proto.RegisterType((*Selector)(nil), "registrar.Selector")
	proto.RegisterType((*SelectorList)(nil), "registrar.SelectorList")
}

func init() { proto.RegisterFile("registrar.proto", fileDescriptor_8f352f3dd33231ae) }

var fileDescriptor_8f352f3dd33231ae = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x65, 0x13, 0x42, 0xe3, 0x69, 0x04, 0x66, 0x8b, 0x54, 0x2b, 0x2d, 0x28, 0xf2, 0x29, 0xaa,
	0x44, 0x0c, 0x41, 0x9c, 0xb8, 0x90, 0x14, 0x14, 0x05, 0x4a, 0xa8, 0x9c, 0xa0, 0x48, 0xbd, 0x39,
	0xce, 0xd8, 0x32, 0x71, 0xba, 0xc6, 0xbb, 0x46, 0xb2, 0xf8, 0x26, 0x3e, 0x8a, 0xbf, 0xe0, 0x88,
	0xec, 0x78, 0xed, 0x75, 0x49, 0x11, 0x1c, 0xb8, 0xed, 0xce, 0x7b, 0x33, 0xf3, 0xde, 0xce, 0xee,
	0xc2, 0x83, 0x18, 0xfd, 0x80, 0x8b, 0xd8, 0x89, 0x07, 0x51, 0xcc, 0x04, 0xa3, 0x5a, 0x19, 0xe8,
	0x9e, 0xf8, 0x8c, 0xf9, 0x21, 0x5a, 0x39, 0xb0, 0x4a, 0x3c, 0x0b, 0xb7, 0x91, 0x48, 0x77, 0x3c,
	0xf3, 0x3b, 0x81, 0x23, 0x3b, 0xa7, 0x62, 0x3c, 0x63, 0x6b, 0xb4, 0xf1, 0x4b, 0x82, 0x5c, 0x50,
	0x1d, 0x9a, 0xef, 0x96, 0x0b, 0x83, 0xf4, 0x48, 0x5f, 0xb3, 0xb3, 0x25, 0xb5, 0xa0, 0x9d, 0x11,
	0x16, 0x69, 0x84, 0x46, 0xa3, 0x47, 0xfa, 0xf7, 0x87, 0x47, 0x83, 0xaa, 0xab, 0x84, 0xec, 0x92,
	0x44, 0x5f, 0x82, 0x36, 0xc7, 0x10, 0x5d, 0xc1, 0x62, 0x6e, 0x34, 0x7b, 0xa4, 0x7f, 0x38, 0x3c,
	0x56, 0x32, 0x24, 0x76, 0x11, 0x70, 0x61, 0x57, 0x4c, 0x7a, 0x0a, 0x5a, 0x56, 0x62, 0x12, 0xb3,
	0x24, 0x32, 0xee, 0xe6, 0xfd, 0xab, 0x80, 0xf9, 0x83, 0xc0, 0xb1, 0xd4, 0xbb, 0x64, 0xf1, 0x26,
	0x64, 0xce, 0xfa, 0x76, 0xcd, 0xaf, 0xa0, 0x23, 0x49, 0x8a, 0x6e, 0x55, 0x85, 0x0a, 0xdb, 0x35,
	0xf2, 0x7f, 0xd1, 0x4f, 0xcd, 0x4a, 0xd1, 0xcc, 0xd9, 0xa2, 0xd1, 0xca, 0x09, 0xb5, 0x98, 0x39,
	0x00, 0x5d, 0x5a, 0xb4, 0x91, 0x47, 0xec, 0x9a, 0x23, 0xed, 0x42, 0x9b, 0x47, 0x81, 0xe7, 0xe1,
	0xf4, 0x4d, 0x61, 0xb0, 0xdc, 0x9b, 0xdf, 0xe0, 0xe1, 0x04, 0xc5, 0xc8, 0x75, 0x59, 0x72, 0x2d,
	0xe4, 0x61, 0xd4, 0xd4, 0x93, 0xbf, 0x56, 0xff, 0xaf, 0x53, 0x36, 0x2f, 0x80, 0xaa, 0xcd, 0x0b,
	0xb9, 0x06, 0x1c, 0x14, 0xa1, 0x42, 0xad, 0xdc, 0xd6, 0x8f, 0xa7, 0x71, 0x73, 0xbc, 0x43, 0x68,
	0x4b, 0x2d, 0xd9, 0x38, 0x37, 0x98, 0xca, 0x71, 0x6e, 0x30, 0xa5, 0x8f, 0xa0, 0xf5, 0xd5, 0x09,
	0x13, 0x2c, 0xf2, 0x76, 0x1b, 0x73, 0x04, 0x1d, 0xd5, 0x0d, 0x7d, 0x5e, 0x77, 0xde, 0xec, 0x1f,
	0xd6, 0x3c, 0x48, 0x4c, 0x71, 0x7d, 0xf6, 0xac, 0x72, 0x4d, 0x0f, 0xa0, 0xb9, 0xb8, 0xfc, 0xa0,
	0xdf, 0xc9, 0x16, 0x93, 0xf3, 0x4b, 0x9d, 0x64, 0x8b, 0xd1, 0x72, 0xae, 0x37, 0xa8, 0x06, 0xad,
	0xd1, 0xd5, 0x27, 0xfb, 0xad, 0xde, 0x3c, 0xeb, 0xd5, 0x6f, 0x56, 0xc6, 0xf9, 0x78, 0x3e, 0xdd,
	0x65, 0x8d, 0xa7, 0x33, 0x9d, 0x0c, 0x7f, 0x12, 0xd0, 0x6c, 0xd9, 0x95, 0xbe, 0x87, 0x8e, 0xfa,
	0xcc, 0xe8, 0x13, 0x45, 0xd1, 0x9e, 0xf7, 0xd7, 0x3d, 0xd9, 0x83, 0x97, 0xa7, 0x3b, 0xaf, 0x2e,
	0x88, 0x14, 0x41, 0xcd, 0x3d, 0x09, 0x37, 0x1e, 0xc8, 0x9f, 0x8b, 0x4e, 0x01, 0xaa, 0x41, 0xd2,
	0x53, 0x85, 0xfa, 0xdb, 0xe5, 0xea, 0x3e, 0xbe, 0x05, 0xdd, 0x95, 0x1a, 0x8f, 0xaf, 0x5e, 0xfb,
	0x81, 0x08, 0x9d, 0xd5, 0xc0, 0x65, 0x5b, 0x4b, 0x20, 0x17, 0x81, 0x97, 0x72, 0x74, 0xad, 0xcf,
	0xc9, 0xda, 0xc7, 0xa7, 0x51, 0xe8, 0x08, 0x8f, 0xc5, 0x5b, 0xab, 0x2c, 0x62, 0x45, 0x1b, 0xdf,
	0x72, 0xa2, 0xa0, 0x8a, 0xac, 0xee, 0xe5, 0xff, 0xd3, 0x8b, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x58, 0x34, 0xed, 0x85, 0xda, 0x04, 0x00, 0x00,
}
